export const MOCK_MISSING_PERSONS = [
  {
    name: "김철수",
    age: 65,
    gender: "남성",
    weight: 75,
    height: 170,
    lastSeen: "2024-03-19 14:30",
    address: "중구 세종대로",
    region: ['중구 세종대로 99'],
    description: "검은색 점퍼, 청바지 착용",
    image: "/api/placeholder/120/150",
  },
  {
    name: "이영희",
    age: 8,
    gender: "여성",
    weight: 28,
    height: 125,
    lastSeen: "2024-03-20 16:45",
    address: "중구 세종대로",
    region: ['중구 세종대로 110'],
    description: "분홍색 외투, 흰색 운동화 착용",
    image: "/api/placeholder/120/150",
  },
];